#pragma once

#define SHADER_VERTEX_BIT 0
#define SHADER_COLOR_BIT 1
#define SHADER_TEX_BIT 2
#define SHADER_BRIG_BIT 3
#define SHADER_COLOR_FLAG    (1 << SHADER_COLOR_BIT)
#define SHADER_TEXTURE_FLAG  (1 << SHADER_TEX_BIT)
#define SHADER_BRIG_FLAG     (1 << SHADER_BRIG_BIT)
