#include "Rubydung.h"

#include <Host/init.h>
#include <Utils/Util.h>
#include <App/Application.h>

#include "..\build.h" /* autogenerated header (view update_counter.bat) */

#define COUNTER_INTERFACE     1
#define TPS                   60.0f
#define WIN_X                 1024
#define WIN_Y                 768
#define WIN_TITLE             "Game"

using namespace MC::App;

class Game : public Application {
public:
	Game()
		: Application(WIN_TITLE, { WIN_X, WIN_Y, { false } })
	{ }

	~Game()
	{ }

	void Init() override
	{
		Application::Init();

		PushLayer(new Rubydung());
	}
};

int main(int argc, char** argv) {
	mc_host_init(argc, argv);
	mc_init_log(1, CONSOLE_MODE);

#if defined (COUNTER_INTERFACE)
	MC_WARN("RubyDung rd-133221 build: %i", BUILD_COUNT);
#endif

	/* initialize random number generator */
	srand(time(NULL));

	Game game;
	game.Start();
	return 0;
}