help:
	@echo "make - MC Rewrite main build system"
	@echo ""
	@echo "usage: make <target>"
	@echo ""
	@echo "Cleaning Targets:"
	@echo "clean              - Remove contents of build/ directory"
	@echo "distclean          - Remove build/ directory"
	@echo "clean-core         - Remove MC core build files"
	@echo "clean-sandbox      - Remove game build files"
	@echo "clean-deps-install - Remove all INSTALLED files in Dependencies/ directory"
	@echo "clean-deps-build   - Remove all BUILDED files in Dependencies/ directory"
	@echo ""
	@echo "Building Targets:"
	@echo "all                - Build all MC project files. this doesn't include Dependencies/ directory"
	@echo "                     Before you build MC project you MUST install dependencies yourself or using"
	@echo "                     make build-deps"
	@echo "core               - Build MC engine"
	@echo "sandbox            - Build Game"
	@echo "build-deps         - Build and install all in the Dependencies/ directory"
	@echo ""
	@echo "Install Targets:"
	@echo "install-deps       - Install Dependencies/ from local repositories (not build)"
	@echo ""
	@echo "Misc Targets:"
	@echo "help               - View help message"
	@echo "run                - Run game"
	@echo "make DEBUG=1       - Enable debug mode"
	

